services:
  portainer-practices:
    image: venukishore/portainer-practices:1.0.0
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 2s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - portainer-practices
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
